#ifndef LIBVIDEOTOOLS_GLOBAL_H
#define LIBVIDEOTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBVIDEOTOOLS_LIBRARY)
#  define LIBVIDEOTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBVIDEOTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBVIDEOTOOLS_GLOBAL_H
